### ISSUE TITLE
Made a fork, cannot create PR from it

### ISSUE THREAD

**Issue by akrk1986** [chriskiehl/re-wx#1]
Hello Chris,
Looks like an awesome project! 
While reading the docs, I noticed some minor issues, so I've forked the repo and made some changes to the documentation (.md files), but I cannot push my branch to your repo (I get error 403).

Please advise.
Thanks,
Amir

**Comment by chriskiehl** [comment]
Howdy! 

Are you trying to push directly to re-wx's repo? If so, you'll surely see those 403s. 

You should be able to create a PR through Github's interface which'll put everything in the right shape for me to review and merge. One the branch you've changed, you should see something like this: 

<img width="918" alt="image" src="https://user-images.githubusercontent.com/1408720/105913801-3ddbe180-5fe2-11eb-8d76-6a170bf2041c.png">

Clicking the Pull Request button should get you in the right area.
