### ISSUE TITLE
Notes on core.py

### ISSUE THREAD

**Issue by jamesdbrock** [chriskiehl/re-wx#14]
`self_managed` seems like a useful attribute. It’s not mentioned anywhere else in the package, but this implementation seems reasonable and maybe it works?

https://github.com/chriskiehl/re-wx/blob/882967e5cbe14a2b65f45b5cfccea3cccdb293f4/rewx/core.py#L86

`component_will_unmount` is never called anywhere, so this feature is not yet implemented.

https://github.com/chriskiehl/re-wx/blob/882967e5cbe14a2b65f45b5cfccea3cccdb293f4/rewx/core.py#L195

This __re-wx__ package seems like the best cross-platform native GUI Python package on the internet. Or anyway, the least insane. Everything else is either web-based (Streamlit), or 20th-century object-oriented trash (QT for Python), or looks so horrible that you can’t distribute it to any users. (DearPyGUI).

But the __Alpha Note__ on the README is not just false modesty. This package really is not yet reliable. Is there any possibility that you will resume your interest in this project @chriskiehl ? I would like to work on improvement to __re-wx__ but my Python is bad and I don’t understand the code for __re-wx__ as well as you. Reading the code, I feel like you had a roadmap for __re-wx__ in your head, but you didn’t have time to work it all out. What are your thoughts on the future of this package?

**Comment by jamesdbrock** [comment]
There is also https://github.com/fding/pyedifice , which is in about the same partially-finished condition as __re-wx__.

When I research “declarative” “Elm architecture” “virtual DOM” native GUIs for Python I see a lot of agreement that this should exist, but no-one has yet accomplished it. I think the __re-wx__ approach is the most promising.

**Comment by jamesdbrock** [comment]
`updatewx` appears to be some kind of hack for native components, but it’s not called from anywhere?

https://github.com/chriskiehl/re-wx/blob/882967e5cbe14a2b65f45b5cfccea3cccdb293f4/rewx/core.py#L47

**Comment by chriskiehl** [comment]
Howdy! 

Glad to hear you've gotten some use out of the project! Dragging Python into the declarative world was indeed the initial goal of the project. I still think there's a pretty good niche that could be carved out here. However, the best it'll ever be is a niche. It's not going to compete with, say, [Electron](https://www.electronjs.org/). The demand for the type of program built from native widgets in 2022 seems vanishingly small. 

When initially written, my grand plans for the framework involved creating a serious competitor in the Python GUI landscape. However, there wasn't as much demand as I thought, and open source doesn't pay the bills, so the future of this project is now scoped to mostly just being "good enough" to support my needs while developing [Gooey](https://github.com/chriskiehl/Gooey). It'll receive maintenance updates as needed for that use case. 

Cheers!

**Comment by jamesdbrock** [comment]
Thanks for the note @chriskiehl , and thanks for all the work you’ve done on __re-wx__.

__Gooey__ is a very nice project, and it has 16K stars, and I see that it depends on __re-wx__, which is nice to know, because that reassures me that __re-wx__ will not be completely neglected.

I'm going to keep trying to use __re-wx__, and I'll submit PRs as much as possible.

**Comment by jamesdbrock** [comment]
( Love this blog post https://chriskiehl.com/article/webscraping-on-hard-mode )

**Comment by jamesdbrock** [comment]
Here's an example of a `self_managed` component: https://github.com/chriskiehl/Gooey/blob/be4b11b8f27f500e7326711641755ad44576d408/gooey/gui/components/config.py#L15
