### ISSUE TITLE
Why so many Layout()s?

### ISSUE THREAD

**Issue by jamesdbrock** [chriskiehl/re-wx#15]
https://github.com/chriskiehl/re-wx/blob/882967e5cbe14a2b65f45b5cfccea3cccdb293f4/rewx/core.py#L140-L143

https://docs.wxpython.org/wx.Window.html#wx.Window.Layout

Every time an element gets `patch`ed, `Layout()` is called on all the element’s transitive parents.

So if an element has *N* transitive children, then `Layout()` will be called on the element *N* times during each render.

Is that deliberate? Seems expensive? Why is that necessary?

**Comment by chriskiehl** [comment]
>Is that deliberate? 

Very little of re-wx is deliberate ^_^ The bulk of it was hacked together over a few frantic days of coding while I was on vacation. Calling `Layout()` everywhere was surely just a bit of duct tape to solve whatever layout quirks I was experiencing at the time. 

As for the expense, I'm not sure. Probably depends on how deep your tree is. However, I suspect its cost pales in comparison to the way reconciliation is currently handled on each render (which just blanket removes / recreates all child components anytime the model and the real world disagree (i.e. what `key` exists the solve in React)). Bench marking is needed.

**Comment by jamesdbrock** [comment]
Thanks, your commentary is really helpful to me to understand what's happening in `core.py`, and what might be improved.

**Comment by jamesdbrock** [comment]
I've been looking at some profiling of re-wx, this is a sample of what I'm seeing (from [pstats](https://docs.python.org/3/library/profile.html))

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1   10.082   10.082   17.664   17.664 {MainLoop}
       85    0.353    0.004    0.353    0.004 {built-in method SetBitmap}
  3864/84    0.305    0.000    6.774    0.081 C:\Users\jbrock\work\JIT_GUI\./submodule/re-wx\rewx\core.py:66(patch)
        1    0.255    0.255    0.617    0.617 C:\Users\jbrock\work\JIT_GUI\jitapp.py:239(discover_state)
       85    0.240    0.003    0.240    0.003 {built-in method Append}
        1    0.206    0.206    1.825    1.825 C:\Users\jbrock\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\__init__.py:1(<module>)
       84    0.188    0.002    0.188    0.002 {built-in method Thaw}
      631    0.186    0.000    0.186    0.000 {built-in method io.open_code}
     4995    0.183    0.000    0.386    0.000 <frozen importlib._bootstrap_external>:96(_path_join)
65369/62697    0.161    0.000    0.191    0.000 {built-in method builtins.isinstance}
       84    0.151    0.002    0.151    0.002 {built-in method Freeze}
    46243    0.117    0.000    0.117    0.000 {method 'startswith' of 'str' objects}
     2858    0.110    0.000    0.110    0.000 {built-in method nt.stat}
     3825    0.104    0.000    0.330    0.000 C:\Users\jbrock\work\JIT_GUI\./submodule/re-wx\rewx\widgets.py:72(set_basic_props)
       84    0.101    0.001    0.101    0.001 {Create}
    14785    0.095    0.000    0.134    0.000 C:\Users\jbrock\AppData\Local\Programs\Python\Python310\lib\site-packages\wx\core.py:2360(_Window___nonzero__)
      120    0.089    0.001    7.216    0.060 C:\Users\jbrock\work\JIT_GUI\jitapp.py:698(handle_motion)
       84    0.081    0.001    0.081    0.001 {built-in method Flush}
     3698    0.076    0.000    0.209    0.000 C:\Users\jbrock\AppData\Local\Programs\Python\Python310\lib\site-packages\wx\core.py:3406(CallAfter)
31006/30121    0.075    0.000    0.080    0.000 {built-in method builtins.len}
       85    0.074    0.001    0.074    0.001 C:\Users\jbrock\AppData\Local\Programs\Python\Python310\lib\site-packages\wx\core.py:752(_Image_ConvertToBitmap)
```
